### ISSUE TITLE
No maps shown on certain browsers google chrome and safari - IE11 OK

### ISSUE THREAD

**Issue by umgfoin** [Frank1604/files_gpxviewer_extended#17]
owncloud 9
gpxviewer extended 1.5
chromium  50.0.2634.0 (x64)
chrome 50.0.2661.57(x64)
safari 9.1
IE11

As of current, there're no maps shown, if app is rendered by browsers as google chrome or safari.
Sometimes the map-tile frames become visible, but content is never drawn. Track and rest of GUI is OK..

IE11 rendering same content without issues.

Thanks for your work on this really useful app!
bg umgfoin.

**Comment by olaulau** [comment]
this is due to content-security-policy which seems to be set by owncloud, not allowing other domains to load.
this app has to add openstreemap.org domain to the list of allowed domains, as explained here : https://github.com/owncloud/core/issues/16449#issuecomment-103597716

**Comment by olaulau** [comment]
is it fixed ?

**Comment by Frank1604** [comment]
yes, fixed in version 1.6
