### ISSUE TITLE
Should "Altitude" be labeled as "Ascend" or "Total Ascend" or something???

### ISSUE THREAD

**Issue by C-Makridis** [Frank1604/files_gpxviewer_extended#3]
Maybe I got it wrong, I'm quite new and confused, but I'm trying to add a greek translation and got quite confused with the Altitude string.

Viewing some gpx data, I get the feeling that this is refairing to the "Total Ascend" and not to the Altitude (neither minimum, nor maximum).

Am I getting this wrong???

I'd only like to know what it is refering to, so that I can correnctly translate it.

thanks for your time, and please excuse any spelling / grammar mistakes... :)

**Comment by Frank1604** [comment]
Yes you´re right. The meaning is total ascend or total climb. Thanks for the info. :)
