### ISSUE TITLE
We need an GPS tracing Viewer :)

### ISSUE THREAD

**Issue by blackcrack** [Frank1604/files_gpxviewer_extended#8]
Hi, why should we not have an GPS-Viewer for our Handys, Tables, Car's and so on, but anyone should it make, there it is an possible to become maps, by open maps :+1: 

https://www.openstreetmap.org/

on any device where have an GPS it is an unice GPS-number 
for this device and this can we are view per app
and if you make an GPS-Tracking Viewer for Owncloud, can we all tracing our devices.. if it's stolen

best regards
Blacky

**Comment by Frank1604** [comment]
Sounds cool. Feel free to develop such feature. ;)
